version: 1
runtime: custom
vm: true
api_version: 1
threadsafe: yes

manual_scaling:
  instances: 1

handlers:

- url: /(.*\.(gif|png|jpg))$
  static_files: java/app/\1
  upload: java/app/.*\.(gif|png|jpg)$

- url: .*
  script: dynamic