version: 1
runtime: custom
vm: true
api_version: 1
threadsafe: yes

manual_scaling:
  instances: 1

handlers:

- url: /webjars/.*
  script: dynamic

- url: /(.*\.(gif|png|jpg))$
  static_files: app/\1
  upload: app/.*\.(gif|png|jpg)$

- url: /request
  script: dynamic
  login: required

- url: /env
  script: dynamic
  login: required

- url: .*
  script: dynamic